### ISSUE TITLE
Docker for m1

### ISSUE THREAD

**Issue by matheus1lva** [Yohnah-org/Docker#1]
Hi! 
I would like how could i help test and build this on a M1 :D

**Comment by Yohnah** [comment]
Hi and thanks for wanting to help in this project.

The main issue with the M1 processor architecture is that Parallels is the only hypervisor to support M1 using GNU/Linux SO based on ARM chip, so it is needed to develop a Packer code to built a box image to run on ARM architecture on Parallels

It looks like VMWARE Fusion is working on M1 chip as beta version, and Virtualbox seems it won't support M1 chip (or no news I read about it).

So, if you have a Apple M1, you can fork the repository to create a packer code version to create a Vagrant imagen using a GNU/Linux SO for chips based on ARM for parallels hypervisor.

It is a better idea to using a Debian for ARM and you can take advantage about same provision scripts, or, maybe you will have to refactor the current scripts instead.

I figured out a hard issue in the images because of the Vagrant builder for Packer, and I am forced to refactor all packer code to use "-iso" builders (ex: virtualbox-iso, parallels-iso, etc).

I'm gonna perform the changes next weekend, and go the semantic version up to 2.0.0 because incompatibility with current code.

**Comment by Yohnah** [comment]
I close this issue for no more answers in this topics.
